export const actionTypes = {
    GET_GAMES:"GET_GAMES",
    LOGIN_USER:"LOGIN_USER",
    SET_USER:"SET_USER",
    SET_GAMES : "SET_GAMES",
    GET_ROLES : "GET_ROLES",
    SET_ROLES : "SET_ROLES",
    MERGE_GAMES : "MERGE_GAMES",
    SET_MERGE_GAMES : "SET_MERGE_GAMES",
    MERGE_ROLES : "MERGE_ROLES",
    SET_MERGE_ROLES : "SET_MERGE_ROLES",
    GET_USERS : 'GET_USERS',
    SET_USERS : 'SET_USERS',
    REGISTER_USER : 'REGISTER_USER',
    SET_REGISTER_RESPONSE : 'SET_REGISTER_RESPONSE'

};